/**
 * Module.Migration.ClientMigrationData
 *
 * DATA MENTAH 127 client lama, ditanam langsung di kode — SENGAJA tidak
 * lewat sheet staging seperti LeadMigrationRepository. Alasannya: jumlahnya
 * kecil dan tetap, dan menanamnya di sini menghapus satu langkah
 * copy-paste manual yang paling gampang salah (kolom tergeser, tanggal
 * terlanjur dikonversi Sheets, baris kepotong).
 *
 * Sudah dirapikan saat digenerate dari CSV sumber:
 * - semua field di-trim (ada 6 field yang ujungnya berspasi di CSV asli);
 * - brand & entitas di-UPPERCASE, mengikuti ClientService.createManualClient
 *   supaya client hasil migrasi tidak terlihat beda dari yang diinput lewat
 *   aplikasi;
 * - Website tanpa skema dilengkapi https:// (torch.id);
 * - tgl = [tahun, bulan, tanggal, jam, menit, detik] hasil parsing M/D/YYYY
 *   dari CSV. Disimpan sebagai angka, BUKAN string, supaya tidak ada lagi
 *   tebak-tebakan apakah "5/6/2026" itu 5 Juni atau 6 Mei (jawabannya: 6 Mei,
 *   format sumbernya M/D/YYYY).
 *
 * Field yang di CSV 100% kosong (Created_By, Last_Updated, Other_Notes,
 * Is_From_Lead, Entity_Type_Other) sengaja TIDAK ikut ditanam — nilainya
 * ditentukan saat impor di ClientMigrationService.
 *
 * JANGAN diedit manual. Kalau datanya berubah, generate ulang dari CSV.
 */
var ClientMigrationData = (function (module) {

  module.RECORDS = [
    { id:"CL26-00034", brand:"PUNDI ASA", entitas:"YAYASAN PUNDI ASA MANUSIA", tipe:"Institusi Sosial", kota:"Kota Jakarta Selatan", web:"https://pundiasa.com/id", industri:"", sumber:"Referral", tgl:[2026,5,6,16,58,39] },
    { id:"CL26-00035", brand:"UNBRAW", entitas:"NAPAK TILAS UNIVERSITAS BRAWIJAYA", tipe:"Lembaga Pendidikan", kota:"Kota Malang", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,16,58,39] },
    { id:"CL26-00036", brand:"KONHICIWA GRUP", entitas:"PT LIMA PILAR SENTOSA", tipe:"Perusahaan", kota:"Kota Jakarta Barat", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,16,58,39] },
    { id:"CL26-00037", brand:"GREAT EASTERN LIFE INSURANCE", entitas:"PT GREAT EASTERN LIFE INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.greateasternlife.com/", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00038", brand:"KENVUE - AVEENO", entitas:"PT JOHNSON JOHNSON INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.kenvuebrands.com/id", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00039", brand:"SHOOPEE", entitas:"PT SHOPEE INTERNATIONAL INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00040", brand:"FLIP", entitas:"PT FLIPTECH LENTERA INSPIRASI PERTIWI", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00041", brand:"TOKOPEDIA", entitas:"PT TOKOPEDIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00042", brand:"CIMB NIAGA", entitas:"PT BANK CIMB NIAGA TBK", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00043", brand:"BENEVITY", entitas:"BENEVITY", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://benevity.com/", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00044", brand:"YBB", entitas:"YOUTH BREAK THE BOUNDARIES", tipe:"Institusi Sosial", kota:"Kota Jakarta Selatan", web:"https://youthbreaktheboundaries.com/", industri:"", sumber:"Outbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00045", brand:"FORD FOUNDATION", entitas:"FORD FOUNDATION", tipe:"Institusi Sosial", kota:"Kota Jakarta Selatan", web:"https://www.fordfoundation.org/", industri:"", sumber:"Outbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00046", brand:"CHICKIN", entitas:"PT SINERGI KETAHANAN PANGAN", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://chickin.id/", industri:"", sumber:"Outbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00047", brand:"EAI FOUNDATION", entitas:"YAYASAN EDUCATION AID INTERNATIONAL", tipe:"Institusi Sosial", kota:"Kota Jakarta Selatan", web:"https://eaifoundation.org/", industri:"", sumber:"Outbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00048", brand:"TELKOMSEL POIN", entitas:"PT TELEKOMUNIKASI SELULAR", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Outbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00049", brand:"GARUDA MILES", entitas:"PT GARUDA INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Outbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00050", brand:"ZURICH INDONESIA", entitas:"PT ZURICH ASURANSI INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"", industri:"Financial Services", sumber:"Outbound", tgl:[2026,5,6,0,0,0], pic:{nama:"Sri Rizki Kesumaningrum (Kiki)",jabatan:"CORPORATE SOCIAL RESPONSIBILITY MANAGER",email:"s.kesumaningrum@zurich.co.id",telepon:"6281908198196"} },
    { id:"CL26-00051", brand:"PUTERA SAMPOERNA FOUNDATION (PSF)", entitas:"PUTERA SAMPOERNA FOUNDATION", tipe:"Institusi Sosial", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00052", brand:"ZAP", entitas:"PT ZULU ALPHA PAPA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://zapclinic.com/", industri:"", sumber:"Referral", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00053", brand:"MR.KRIUK", entitas:"PT CERITA KRIUK INDONESIA", tipe:"Perusahaan", kota:"Kota Bogor", web:"https://mrkriuk.id/", industri:"", sumber:"Referral", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00054", brand:"PREKIN", entitas:"PT SETYA KULINER MANDIRI", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://prekin.id/", industri:"", sumber:"Referral", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00055", brand:"VIVI NICI", entitas:"PT KARYA NYATA ALASINDO", tipe:"Perusahaan", kota:"Kota Bogor", web:"https://vivinici.com/", industri:"", sumber:"Referral", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00056", brand:"IDN", entitas:"PT MEDIA PUTRA NUSANTARA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.idn.media/", industri:"", sumber:"Referral", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00057", brand:"PMN", entitas:"PT PRIMA MAHAKARYA NUSANTARA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://companiesfacts.id/prima-mahakarya-satu", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00058", brand:"PT MATA TOBA", entitas:"PT MATA TOBA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,16,58,39] },
    { id:"CL26-00059", brand:"BME", entitas:"PT BERKAT MANUNGGAL ENERGI", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.bmepower.com/", industri:"", sumber:"Inbound", tgl:[2026,5,6,16,58,39] },
    { id:"CL26-00060", brand:"SEDEKAH CUKUR", entitas:"SC", tipe:"Event", kota:"Kota Jakarta Pusat", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,16,58,39] },
    { id:"CL26-00061", brand:"SEDJUK BAKMI", entitas:"PT TULODONG DELAPANBELAS SEJAHTERA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://sedjuk.com/", industri:"", sumber:"Inbound", tgl:[2026,5,6,16,58,39] },
    { id:"CL26-00062", brand:"GRIYA YODESIYA", entitas:"PT PUSPITA YODESIYA PERKASA", tipe:"Perusahaan", kota:"Kabupaten Semarang", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,16,58,39] },
    { id:"CL26-00063", brand:"MY LITTLE WARUNG", entitas:"PT BLOOMERY SEKAWAN SEJAHTERA", tipe:"Perusahaan", kota:"Yogyakarta", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00064", brand:"STAR ENERGY GEOTHERMAL", entitas:"PT PERTAMINA GEOTHERMAL ENERGY", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00065", brand:"QDC", entitas:"PT QDC TECHNOLOGIES", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.qdc.co.id/", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00066", brand:"WEWAW INDONESIA", entitas:"YAYASAN WEWAW KREASI BERDAYA", tipe:"Institusi Sosial", kota:"Kota Jakarta Selatan", web:"https://www.wewaw.org/", industri:"FMCG", sumber:"Outbound", tgl:[2026,5,6,0,0,0], pic:{nama:"Nydia Verea",jabatan:"COMMUNITY DEVELOPMENT",email:"nydiaverea@gmail.com",telepon:"628118119933"} },
    { id:"CL26-00067", brand:"JNE", entitas:"PT TIKI JALUR NUGRAHA EKAKURIR", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.jne.co.id/profil-perusahaan", industri:"Logistics & Supply Chain", sumber:"Outbound", tgl:[2026,5,6,0,0,0], pic:{nama:"Wahyu Robihun",jabatan:"EMPLOYEE ENGAGEMENT DEPARTMENT HEAD",email:"wahyu.robihun@jne.co.id",telepon:"6285697590764"} },
    { id:"CL26-00068", brand:"SIPNPACK", entitas:"SIPNPACK INDONESIA", tipe:"Perusahaan", kota:"Kota Tangerang Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00069", brand:"BANK PERMATA", entitas:"PT BANK PERMATA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.permatabank.com/id/home/", industri:"Financial Services", sumber:"Outbound", tgl:[2026,5,6,0,0,0], pic:{nama:"Nadya Arfiani Aifin",jabatan:"CSER & SUSTAINABILITY ON SOCIAL IMPACT",email:"nadya.arifin@permatabank.co.id",telepon:"628119187123"} },
    { id:"CL26-00070", brand:"TUGU INSURANCE", entitas:"PT ASURANSI TUGU PRATAMA INDONESIA", tipe:"Komu", kota:"Kota Jakarta Selatan", web:"https://tugu.com/", industri:"", sumber:"Outbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00071", brand:"SCORA", entitas:"PT ORE INTERNATIONAL DISTRIBUTION", tipe:"Perusahaan", kota:"Kota Tangerang Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00072", brand:"CLT TOOLBOX", entitas:"PT CLT TOOLBOX INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://spectoolbox.com/", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00073", brand:"TMII", entitas:"TAMAN MINI INDONESIA INDAH", tipe:"Pemerintahan", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00074", brand:"MY PERTAMINA", entitas:"PT PERTAMINA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://mypertamina.id/", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00075", brand:"BY.U", entitas:"PT TELEKOMUNIKASI SELULAR", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00076", brand:"RUN4SUMATRA", entitas:"RUN4SUMATRA", tipe:"Komunitas", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00077", brand:"KOMPASIANA", entitas:"PT KOMPAS CYBER MEDIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.kompasiana.com/syarat-ketentuan#:~:text=Hak%20cipta%20dan%20merek%20dagang%20Kompasiana%20dimiliki%20oleh%20PT%20Kompas%20Cyber%20Media.", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00078", brand:"PT ASIA PASIFIK GOLF MEDIA", entitas:"PT ASIA PASIFIK GOLF MEDIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00079", brand:"MULTIPOLAR", entitas:"PT MULTIPOLAR", tipe:"Perusahaan", kota:"Kota Tangerang", web:"https://www.multipolar.com/", industri:"", sumber:"Outbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00080", brand:"MAZII", entitas:"MAZII", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://mazii.net/id-ID/search", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00081", brand:"GLAMSHINE", entitas:"PT BARIQ JAYA SENTOSA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00082", brand:"CLUB SI PALING PADEL", entitas:"CLUB SI PALING PADEL", tipe:"Komunitas", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00083", brand:"INDOZONE", entitas:"PT INDOZONE MEDIA INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.indozone.id/", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00084", brand:"KG MEDIA", entitas:"KOMPAS GRAMEDIA GROUP OF MEDIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.kgmedia.id/", industri:"", sumber:"Referral", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00085", brand:"JAGO COFFEE", entitas:"PT SOLUSI SATUAN BERJALAN", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.jagocoffee.com/", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00086", brand:"ASOSIASI INDONESIA SWISS", entitas:"ASOSIASI INDONESIA SWISS", tipe:"Institusi Sosial", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00087", brand:"KEARNEY", entitas:"KEARNEY", tipe:"Institusi Sosial", kota:"Kota Jakarta Selatan", web:"", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00088", brand:"LIBERTY SOCIETY FOUNDATION", entitas:"LIBERTY SOCIETY FOUNDATION", tipe:"Institusi Sosial", kota:"Kota Jakarta Selatan", web:"https://liberty-society.com/pages/house-by-liberty", industri:"", sumber:"Referral", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00089", brand:"MAREIN", entitas:"PT MASKAPAI REASURANSI INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://marein-re.com/", industri:"", sumber:"Referral", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00090", brand:"DOUGH LAB", entitas:"PT ASHARIA KARYA INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://doughlab.com/", industri:"", sumber:"Inbound", tgl:[2026,5,6,0,0,0] },
    { id:"CL26-00091", brand:"ENGLISH 1", entitas:"PT ECOM CONSULTING", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://english1.co.id/", industri:"FMCG", sumber:"Inbound", tgl:[2026,5,8,17,36,43] },
    { id:"CL26-00092", brand:"SMILJAN", entitas:"SMILJAN", tipe:"Perusahaan", kota:"Kota Tangerang Selatan", web:"https://manual.co.id/directory/smiljan-space/", industri:"FMCG", sumber:"Inbound", tgl:[2026,5,8,17,40,27] },
    { id:"CL26-00093", brand:"ADMEDIKA", entitas:"PT ADMINISTRASI MEDIKA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.admedika.co.id", industri:"FMCG", sumber:"Inbound", tgl:[2026,5,8,17,48,42] },
    { id:"CL26-00094", brand:"BUMA", entitas:"PT BUKIT MAKMUR MANDIRI UTAMA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://bumainternational.com/", industri:"FMCG", sumber:"Outbound", tgl:[2026,5,8,18,9,54], pic:{nama:"Marwalton Kemit",jabatan:"MANAGER EXTERNAL RELATIONS",email:"marwalton.kemit@bukitmakmur.com",telepon:"6281196503414"} },
    { id:"CL26-00095", brand:"KPEI", entitas:"PT KLIRING PENJAMINAN EFEK INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.idclear.co.id/id/tentang-kpei/profil-perusahaan", industri:"Financial Services", sumber:"Inbound", tgl:[2026,5,11,17,14,38] },
    { id:"CL26-00096", brand:"ALLO FRESH", entitas:"PT ALLO FRESH INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://allofresh.id/", industri:"Retail & E-Commerce", sumber:"Inbound", tgl:[2026,5,11,17,42,11] },
    { id:"CL26-00097", brand:"PTBA", entitas:"PT BUKIT ASAM TBK", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.ptba.co.id/", industri:"Mining", sumber:"Referral", tgl:[2026,5,11,17,50,17], pic:{nama:"A",jabatan:"",email:"",telepon:"6281212341234"} },
    { id:"CL26-00098", brand:"MOVES.ID", entitas:"MOVES.ID", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.instagram.com/movesofficial.id/", industri:"FMCG", sumber:"Inbound", tgl:[2026,5,12,9,31,58], pic:{nama:"Dhyano",jabatan:"",email:"",telepon:"6281585859096"} },
    { id:"CL26-00099", brand:"BALI NEXUS", entitas:"PT. BALI NEXUS INVESTMENTS PARTNERS", tipe:"Perusahaan", kota:"Denpasar", web:"https://balinexusglobal.com/", industri:"Financial Services", sumber:"Referral", tgl:[2026,5,12,10,53,21], pic:{nama:"Emma",jabatan:"",email:"",telepon:"62895360093152"} },
    { id:"CL26-00100", brand:"YAYASAN RENJANA WIDYA SANTI", entitas:"YAYASAN RENJANA WIDYA SANTI", tipe:"Institusi Sosial", kota:"Kota Semarang", web:"", industri:"NGO & Non-Profit Organization", sumber:"Referral", tgl:[2026,5,12,14,26,10], pic:{nama:"Lisa",jabatan:"",email:"",telepon:"628118383073"} },
    { id:"CL26-00101", brand:"ITC", entitas:"PT INTERNATIONAL TEST CENTER", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://itc-indonesia.com/my-account/", industri:"FMCG", sumber:"Inbound", tgl:[2026,5,12,14,29,4], pic:{nama:"Bagus",jabatan:"BUSSINESS COMMUNICATION TEAM LEADER",email:"bagusadi.application@gmail.com",telepon:"6285772668436"} },
    { id:"CL26-00102", brand:"FYP BEAUTY", entitas:"FYP BEAUTY", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.instagram.com/findyourpick.beauty/", industri:"FMCG", sumber:"Inbound", tgl:[2026,5,12,14,34,14], pic:{nama:"Shindy",jabatan:"OWNER",email:"shindysamuel888@gmail.com",telepon:"6282180808808"} },
    { id:"CL26-00103", brand:"MEDCO", entitas:"PT MEDCO ENERGI INTERNASIONAL TBK", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.medcoenergi.com/", industri:"Energy & Utilities", sumber:"Inbound", tgl:[2026,5,12,14,39,41], pic:{nama:"Adel",jabatan:"CSR OFFICER",email:"delthia.saraswati@medcoenergi.com",telepon:"6282121999881"} },
    { id:"CL26-00104", brand:"UOB ASSET MANAGEMENT", entitas:"PT UOB ASSET MANAGEMENT INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.uobam.co.id/index.html", industri:"Financial Services", sumber:"Inbound", tgl:[2026,5,12,14,43,34], pic:{nama:"Charlene",jabatan:"MARKETING COMMUNICATION",email:"charlene.felicita@uob.co.id",telepon:"6287888833790"} },
    { id:"CL26-00105", brand:"ADAKAMI.ID", entitas:"PT PEMBIAYAAN DIGITAL INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.adakami.id/", industri:"Fintech", sumber:"Referral", tgl:[2026,5,12,14,45,56], pic:{nama:"Hanadia",jabatan:"",email:"hanadia@adakami.id",telepon:"6282211725713"} },
    { id:"CL26-00106", brand:"COSMAX", entitas:"PT. COSMAX INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://cosmax.co.id/", industri:"Healthcare & Pharmaceutical", sumber:"Inbound", tgl:[2026,5,12,17,41,41], pic:{nama:"Octa",jabatan:"",email:"octviana@cosmax.com",telepon:"6283895704886"} },
    { id:"CL26-00107", brand:"PT ENKRIPSI TEKNOLOGI HANDAL", entitas:"BYBIT", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.bybit.com/", industri:"Financial Services", sumber:"Referral", tgl:[2026,6,2,16,8,37], pic:{nama:"Faisal Mujaddid",jabatan:"PR & SEARCH GTM (INDONESIAN MARKET)",email:"faisal.mujaddid_os@bybit.com",telepon:"6285159359353"} },
    { id:"CL26-00108", brand:"WARDAH", entitas:"PT PARAGON TECHNOLOGY AND INNOVATION", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"", industri:"FMCG", sumber:"Outbound", tgl:[2026,6,10,13,49,6], pic:{nama:"Mohammad Muhajjalin",jabatan:"OMNICHANNEL MEDIA AND STRATEGIC PARTNERSHIP LEAD",email:"moh.gmuhajjalin@paracorpgroup.com",telepon:"6281333275533"} },
    { id:"CL26-00109", brand:"ZURICH FOUNDATION", entitas:"Z ZURICH FOUNDATION", tipe:"Institusi Sosial", kota:"Kota Jakarta Pusat", web:"", industri:"NGO & Non-Profit Organization", sumber:"Outbound", tgl:[2026,6,10,14,1,12], pic:{nama:"Sri Rizki Kesumaningrum (Kiki)",jabatan:"CORPORATE SOCIAL RESPONSIBILITY MANAGER",email:"s.kesumaningrum@zurich.co.id",telepon:"6281908198196"} },
    { id:"CL26-00110", brand:"FORD FOUNDATION", entitas:"FORD FOUNDATION", tipe:"Institusi Sosial", kota:"", web:"", industri:"NGO & Non-Profit Organization", sumber:"Outbound", tgl:[2026,6,10,14,27,13], pic:{nama:"Gloria Kezia Loupatty (Kezia)",jabatan:"PROGRAM ASSOCIATE",email:"k.loupatty@fordfoundation.org",telepon:""} },
    { id:"CL26-00111", brand:"DANCOW", entitas:"PT NESTLÉ INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.akudankau.co.id/", industri:"Food & Beverage (F&B)", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Lusiana Teguh",jabatan:"COUNTRY MEDIA DIRECTOR L’ORÉAL INDONESIA",email:"lusiana.teguh@loreal.com",telepon:"6281932952722"} },
    { id:"CL26-00112", brand:"PALOMA FOUNDATION", entitas:"PALOMA SJAHRIR FOUNDATION", tipe:"Institusi Sosial", kota:"Kota Jakarta Pusat", web:"https://www.paloma.org/", industri:"NGO & Non-Profit Organization", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Kristal Amalia",jabatan:"HEAD OF PARTNERSHIP",email:"",telepon:""} },
    { id:"CL26-00113", brand:"BICARA UDARA", entitas:"YAYASAN UDARA ANAK BANGSA (YUAB)", tipe:"Institusi Sosial", kota:"Kota Jakarta Pusat", web:"https://bicaraudara.id/", industri:"NGO & Non-Profit Organization", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Kristal Amalia",jabatan:"HEAD OF PARTNERSHIP",email:"",telepon:""} },
    { id:"CL26-00114", brand:"CERAVE", entitas:"PT L'ORÉAL INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.cerave.co.id/", industri:"FMCG", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Didit Darmawan",jabatan:"COUNTRY MEDIA DIRECTOR L’ORÉAL INDONESIA",email:"didit.darmawan@loreal.com",telepon:"6287721337355"} },
    { id:"CL26-00115", brand:"L'OREAL", entitas:"PT L'ORÉAL INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.maybelline.co.id/", industri:"FMCG", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Didit Darmawan",jabatan:"COUNTRY MEDIA DIRECTOR L’ORÉAL INDONESIA",email:"didit.darmawan@loreal.com",telepon:"6287721337355"} },
    { id:"CL26-00116", brand:"BNP PARIBAS", entitas:"PT BANK BNP PARIBAS INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.bnpparibas.co.id/en/", industri:"Financial Services", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Diaz Adiputra Arnan",jabatan:"CREDIT ANALYST",email:"diaz.arnan@asia.bnpparibas.com",telepon:""} },
    { id:"CL26-00117", brand:"GREENWISE CONSULTING", entitas:"GREENWISE CONSULTING (GWC)", tipe:"Perusahaan", kota:"Kota Jakarta Utara", web:"https://greenwise.co.id/", industri:"Professional Services", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Viriya Paramita",jabatan:"MANAGING PARTNER",email:"viriyaparamita@greenwise.co.id",telepon:"6285780123821"} },
    { id:"CL26-00118", brand:"MERDEKA COOPER GOLD", entitas:"PT MERDEKA COPPER GOLD TBK", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://merdekacoppergold.com/", industri:"Mining", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Dinia Widodo",jabatan:"EXTERNAL COMMUNICATIONS MANAGER",email:"",telepon:"6281218619377"} },
    { id:"CL26-00119", brand:"SIDO MUNCUL", entitas:"PT INDUSTRI JAMU DAN FARMASI SIDO MUNCUL TBK", tipe:"Perusahaan", kota:"Kabupaten Semarang", web:"https://www.sidomuncul.co.id/", industri:"Healthcare & Pharmaceutical", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Yuyun",jabatan:"PUBLIC RELATIONS / CORPORATE COMMUNICATIONS",email:"humas@sidomuncul.co.id",telepon:""} },
    { id:"CL26-00120", brand:"MD ENTERTAINMENT", entitas:"PT MD ENTERTAINMENT TBK", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://mdentertainment.com/", industri:"Media, Advertising & Entertainment", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Khushi H",jabatan:"MARKETING ASSOCIATE",email:"khushiharilela123@gmail.com",telepon:"6285780012233"} },
    { id:"CL26-00121", brand:"SEKOLAH CIKAL SURABAYA", entitas:"YAYASAN CINTA KELUARGA", tipe:"Lembaga Pendidikan", kota:"Surabaya", web:"https://www.cikal.co.id/", industri:"Education & EdTech", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Awalia Yusi Ramadhanti",jabatan:"GURU",email:"awalia.ramadhanti@cikal.co.id",telepon:"6289690902777"} },
    { id:"CL26-00122", brand:"SWN PR & ADVISORY", entitas:"SWN PUBLIC RELATIONS & ADVISORY", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://swnpr.com/", industri:"Professional Services", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Sirly Nasir",jabatan:"FOUNDER / MANAGING DIRECTOR",email:"sirly.nasir@swnpr.com",telepon:"628151606021"} },
    { id:"CL26-00123", brand:"ETAWA", entitas:"PT ETHOS KREATIF INDONESIA", tipe:"Perusahaan", kota:"Kabupaten Banyumas", web:"https://ethos.co.id/", industri:"Food & Beverage (F&B)", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Betania Gian",jabatan:"STAKEHOLDER & EMPLOYEE RELATIONS MANAGER",email:"betania.giant@gmail.com",telepon:"6281319081371"} },
    { id:"CL26-00124", brand:"KIN", entitas:"PT ABC KOGEN DAIRY", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://kindairy.com/", industri:"Food & Beverage (F&B)", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Anton Budiharjo",jabatan:"CHIEF COMMERCIAL OFFICER (CCO)",email:"anton.budiharjo@kindairy.com",telepon:"628551086565"} },
    { id:"CL26-00125", brand:"LINTASARTA", entitas:"PT APLIKANUSA LINTASARTA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.lintasarta.net/", industri:"Telecommunication", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Ahmad Sunaryo (Ryo)",jabatan:"CORPORATE COMMUNICATION SENIOR OFFICER",email:"ahmad.sunaryo@lintasarta.co.id",telepon:"6281371213553"} },
    { id:"CL26-00126", brand:"ASURANSI JASINDO", entitas:"PT ASURANSI JASA INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.jasindo.co.id/", industri:"Financial Services", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Amanda Cempaka W. Sudradjat",jabatan:"SENIOR CORPORATE SOCIAL RESPONSIBILITY ANALYST",email:"amanda02809@asuransijasindo.co.id",telepon:"6281289921711"} },
    { id:"CL26-00127", brand:"PT SMI (UNDER KEMENKEU)", entitas:"PT SARANA MULTI INFRASTRUKTUR (PERSERO)", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.ptsmi.co.id/", industri:"Financial Services", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Eka Aditya",jabatan:"",email:"eka@ptsmi.co.id",telepon:"6285697444545"} },
    { id:"CL26-00128", brand:"FWD INSURANCE", entitas:"PT FWD INSURANCE INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.fwd.co.id/", industri:"Financial Services", sumber:"Outbound", tgl:[2026,6,14,15,17,33], pic:{nama:"Pradytha Putri",jabatan:"HEAD OF BRAND AND COMMUNICATIONS",email:"pradytha_putri@linkaja.id",telepon:"6281315099766"} },
    { id:"CL26-00129", brand:"JAECOO INDONESIA", entitas:"PT CHERY SALES INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Utara", web:"https://jaecoo.co.id/", industri:"Automotive", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Afif K Akbar",jabatan:"BRAND MANAGER",email:"",telepon:"628179911585"} },
    { id:"CL26-00130", brand:"KIMIA FARMA", entitas:"PT KIMIA FARMA TBK", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.kimiafarma.co.id/", industri:"Healthcare & Pharmaceutical", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Rafky Putra Asman",jabatan:"ASSISTANT MANAGER CORPORATE SOCIAL RESPONSIBILITY (CSR)",email:"",telepon:"6282388111340"} },
    { id:"CL26-00131", brand:"TASPEN", entitas:"PT TASPEN (PERSERO)", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.taspen.co.id/", industri:"Financial Services", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Elvira Saraswati (Vira)",jabatan:"ASSISTANT PROJECT MANAGER",email:"elvirajuwitasaraswati@gmail.com",telepon:"6282132362643"} },
    { id:"CL26-00132", brand:"OLAHKARSA", entitas:"PT OLAHKARSA INOVASI INDONESIA", tipe:"Perusahaan", kota:"Kota Bandung", web:"https://olahkarsa.com/", industri:"Professional Services", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Rizki Oktavianus",jabatan:"COSTUMER ENGAGEMENT SPECIALIST",email:"",telepon:"62811955006"} },
    { id:"CL26-00133", brand:"INVINYX", entitas:"PT INVINYX PERDANA GEMILANG", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://invinyx.id/", industri:"Media, Advertising & Entertainment", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Dinda Senja",jabatan:"STRATEGIC PLANNER",email:"contact.dindasenja@gmail.com",telepon:"6287700889929"} },
    { id:"CL26-00134", brand:"LIQUID AGENCY", entitas:"PT MITRA WIDYANATHA RELASI", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://liquidagency.co.id/", industri:"Media, Advertising & Entertainment", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Muthia Raidha",jabatan:"ACCOUNT MANAGER",email:"muthia@liquidagency.co.id",telepon:"628569340164"} },
    { id:"CL26-00135", brand:"CANVA", entitas:"OMNICOM GROUP INDONESIA (MEDIA AGENCY)", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.omnicomgroup.com/", industri:"Media, Advertising & Entertainment", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Farhan Siregar",jabatan:"BUSINESS LEAD AT OMNICOM MEDIA GROUP",email:"farhan.siregar@omc.com",telepon:"6282112566098"} },
    { id:"CL26-00136", brand:"KAPAL API", entitas:"PT KAPAL API GLOBAL", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://kapalapiglobal.com/", industri:"Food & Beverage (F&B)", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Annisa Nada Soraya Putri",jabatan:"BRAND EXECUTIVE",email:"",telepon:"6287877676048"} },
    { id:"CL26-00137", brand:"ASTRALIFE", entitas:"PT ASURANSI JIWA ASTRA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.astralife.co.id/", industri:"Financial Services", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Dody Triguno",jabatan:"ASSISTANT MANAGER PUBLIC RELATIONS & CSR",email:"dody.triguno@astralife.co.id",telepon:""} },
    { id:"CL26-00138", brand:"GODREJ", entitas:"PT MEGASARI MAKMUR", tipe:"Perusahaan", kota:"Kabupaten Bogor", web:"https://www.godrejindonesia.com/", industri:"FMCG", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Adrian Junaidar Handayanto",jabatan:"CATEGORY HEAD HOME INSECTICIDES",email:"adrian.junaidar@godrejcp.com",telepon:""} },
    { id:"CL26-00139", brand:"OBM DRILCHEM", entitas:"PT OBM DRILCHEM TBK", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.drilchem.com/", industri:"Mining", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Yuris",jabatan:"",email:"yuris@drilchem.com",telepon:""} },
    { id:"CL26-00140", brand:"GRUNDFOS", entitas:"PT GRUNDFOS POMPA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.grundfos.com/id", industri:"Construction & Engineering", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Dimitra Fitriany",jabatan:"FACILITY MANAGEMENT COORDINATOR",email:"dfitriany@grundfos.com",telepon:""} },
    { id:"CL26-00141", brand:"MOTHER OF PEARL", entitas:"MOTHER OF PEARL", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"http://motherofpearl.id/", industri:"Retail & E-Commerce", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Kavita Krisnamurty",jabatan:"HEAD OF MARKETING",email:"kavita@motherofpearl.id",telepon:""} },
    { id:"CL26-00142", brand:"OREO", entitas:"PT MONDELEZ INDONESIA MANUFACTURING", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.oreo.com/", industri:"Food & Beverage (F&B)", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Deandra Nabilla (Bibil)",jabatan:"SENIOR BRAND MANAGER",email:"deandra.nabilla@mdlz.com",telepon:"628172362630"} },
    { id:"CL26-00143", brand:"RUANG GURU", entitas:"PT RUANG RAYA INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.ruangguru.com/", industri:"Education & EdTech", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Lutfiana Pasebhan Jati (Upik)",jabatan:"SUSTAINABILITY & SOCIAL IMPACT",email:"lutfiana.jati@ruangguru.com",telepon:"6281288730329"} },
    { id:"CL26-00144", brand:"PERMATA BANK", entitas:"PT BANK PERMATA TBK", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.permatabank.com/", industri:"Financial Services", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Nadya Arifin",jabatan:"CSER & SUSTAINABILITY ON SOCIAL IMPACT",email:"nadya.arifin@permatabank.co.id",telepon:"628119187123"} },
    { id:"CL26-00145", brand:"PWC", entitas:"PRICEWATERHOUSECOOPERS INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.pwc.com/id/", industri:"Professional Services", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Rachma Arofani",jabatan:"HUMAN CAPITAL SENIOR MANAGER",email:"rachma.arofani@pwc.com",telepon:"6281294064927"} },
    { id:"CL26-00146", brand:"YAYASAN BAKTI BARITO (YBB)", entitas:"YAYASAN BAKTI BARITO", tipe:"Institusi Sosial", kota:"Kota Jakarta Barat", web:"https://www.baktibarito.com/", industri:"NGO & Non-Profit Organization", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Rinaldi Dwinata S",jabatan:"PROGRAM MANAGER",email:"rinaldi@baktibarito.com",telepon:"6285311264460"} },
    { id:"CL26-00147", brand:"HANA BANK", entitas:"PT BANK KEB HANA INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.hanabank.co.id/", industri:"Financial Services", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Adi Chuardy",jabatan:"SENIOR MANAGER STRATEGY MARKETING COMMUNICATION",email:"adi.chuardy@hanabank.co.id",telepon:"6287882024962"} },
    { id:"CL26-00148", brand:"OK BANK", entitas:"PT BANK OKE INDONESIA TBK", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.okbank.co.id/", industri:"Financial Services", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"David Sinaga",jabatan:"SENIOR BUSINESS RELATIONSHIP MANAGER",email:"david.sinaga@okbank.co.id",telepon:"6281263782609"} },
    { id:"CL26-00149", brand:"DETERJEN SAYANG & KAPAL API GROUP", entitas:"PT KAPAL API GLOBAL", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://kapalapiglobal.com/", industri:"FMCG", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Yulia Kartikasari",jabatan:"AREA SALES AND DISTRIBUTION MANAGER",email:"yulia.kartikasari@kapalapi.co.id",telepon:""} },
    { id:"CL26-00150", brand:"SOFTEX INDONESIA", entitas:"PT SOFTEX INDONESIA", tipe:"Perusahaan", kota:"Kota Tangerang", web:"https://www.softexindonesia.com/", industri:"FMCG", sumber:"Outbound", tgl:[2026,6,14,15,17,34], pic:{nama:"Honey Lestari (Liwe)",jabatan:"GLOBAL SUSTAINABILITY OPERATIONS, SEGMENT SUSTAINABILITY LEADER",email:"",telepon:"6281314081808"} },
    { id:"CL26-00151", brand:"MINISO", entitas:"PT MINISO LIFESTYLE TRADING INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.miniso.id/", industri:"Retail & E-Commerce", sumber:"Outbound", tgl:[2026,6,25,17,12,51], pic:{nama:"Wisnu Prawaba",jabatan:"MARKETING COMMUNICATIONS SPECIALIST",email:"",telepon:"6287809936819"} },
    { id:"CL26-00152", brand:"TORCH", entitas:"PT MAHA NAGARI NUSANTARA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://torch.id", industri:"Retail & E-Commerce", sumber:"Outbound", tgl:[2026,7,3,10,54,5], pic:{nama:"Ben Wirawan",jabatan:"CO-FOUNDER AND CEO",email:"",telepon:"62817206046"} },
    { id:"CL26-00153", brand:"BLUEBAND", entitas:"PT UPFIELD MANUFACTURING INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://padmasaripangan.co.id/pt-upfield/", industri:"FMCG", sumber:"Outbound", tgl:[2026,7,7,15,37,58], pic:{nama:"Metta Marchela Taslim",jabatan:"MARKETING LEAD BLUEBAND",email:"metta.taslim@upfield.com",telepon:"628119111131"} },
    { id:"CL26-00154", brand:"IFF (INTERNATIONAL FLAVORS & FRAGRANCES)", entitas:"PT ESSENCE INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.iff.com/", industri:"FMCG", sumber:"Outbound", tgl:[2026,7,10,16,51,38], pic:{nama:"Oxyana Sara Virgizma (Ochi)",jabatan:"SALES MANAGER",email:"",telepon:"628561256693"} },
    { id:"CL26-00155", brand:"GOJEK", entitas:"PT GOTO GOJEK TOKOPEDIA", tipe:"Perusahaan", kota:"Kota Jakarta Selatan", web:"https://www.gotocompany.com/about-us", industri:"Retail & E-Commerce", sumber:"Referral", tgl:[2026,7,14,14,42,18] },
    { id:"CL26-00156", brand:"MANULIFE INDONESIA", entitas:"PT ASURANSI JIWA MANULIFE INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://www.manulife.co.id/", industri:"Financial Services", sumber:"Outbound", tgl:[2026,7,17,14,57,5] },
    { id:"CL26-00157", brand:"ASURANSI JASINDO", entitas:"PT ASURANSI JASA INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://jasindo.co.id/", industri:"Financial Services", sumber:"Outbound", tgl:[2026,7,17,15,21,59] },
    { id:"CL26-00158", brand:"KRIUK", entitas:"PT CERITA KRIUK INDONESIA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"https://mrkriuk.id/", industri:"FMCG", sumber:"Outbound", tgl:[2026,7,21,12,56,40] },
    { id:"CL26-00159", brand:"GIV", entitas:"PT WINGS SURYA", tipe:"Perusahaan", kota:"Kota Jakarta Pusat", web:"", industri:"FMCG", sumber:"Outbound", tgl:[2026,7,22,12,2,40] },
    { id:"CL26-00160", brand:"4F", entitas:"YAYASAN PETANI PELINDUNG HUTAN", tipe:"Institusi Sosial", kota:"Kota Jakarta Selatan", web:"https://farmers4forest.org/", industri:"NGO & Non-Profit Organization", sumber:"Outbound", tgl:[2026,7,24,16,14,5] }
  ];

  return module;
})(ClientMigrationData || {});
